# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gusev', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-correct', 'date', '-rating'], 'verbose_name': '\u041e\u0442\u0432\u0435\u0442'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date'], 'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u0422\u044d\u0433'},
        ),
        migrations.AlterModelTable(
            name='answer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
