# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gusev', '0002_auto_20170422_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-correct', 'date', '-rating'], 'verbose_name': '\u041e\u0442\u0432\u0435\u0442', 'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c', 'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date'], 'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u0422\u044d\u0433', 'verbose_name_plural': '\u0422\u044d\u0433\u0438'},
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
