# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gusev', '0003_auto_20170422_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
