# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_gusev', '0008_auto_20170422_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerrating',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerrating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questionrating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questionrating',
            name='question',
        ),
        migrations.DeleteModel(
            name='AnswerRating',
        ),
        migrations.DeleteModel(
            name='QuestionRating',
        ),
    ]
